<?php 
/**
 * @category Symmetrics
 * @package Symmetrics_CashTicket
 * @author symmetrics gmbh <info@symmetrics.de>, Eugen Gitin <eg@symmetrics.de>
 * @copyright symmetrics gmbh
 * @license http://opensource.org/licenses/osl-3.0.php  Open Software License (OSL 3.0)
 */
?>

<fieldset class="form-list">
    <?php $_code = $this->getMethodCode() ?>
    <ul id="payment_form_<?php echo $_code ?>" style="display:none">
        <li>
            <p><a href="http://www.cash-ticket.com" target="_blank"><img src="<?php echo $this->getSkinUrl() ?>/images/cashticket/cashticket-logo.png" /></a></p>
            <p><?php echo $this->__('You will be redirected to Cash-Ticket website when you place an order.') ?></p>
        </li>
    </ul>
</fieldset>